### ISSUE TITLE
Tune Up engineering notebook

### ISSUE THREAD

**Issue by colin-szeto** [InspirationRobotics/inspiration_ftc#38]
- [ ] @Dat-Bois  need to update outreach hours document: https://tinyurl.com/tue87v7

- [ ] @Dat-Bois  add documentation about turret design
- [ ] @ colin add documentation about drivetrian design 
 - [ ] @ noah add documentation abotu capstoen design 
- [ ] @ mabel add photos about MegiLion Outreach: https://tinyurl.com/wte5dfz
- [ ] fix/fill in the notebook pages that coach Teresa did.
-[ ] make outreach minute for vist to ForeCast 3d

**Comment by eesh** [comment]
Uh.. Looks like @kolinbilly got the wrong Eesh haha. You probably meant to tag @Dat-Bois
