### ISSUE TITLE
Finish the documentation of the storm robot

### ISSUE THREAD

**Issue by aktang** [InspirationRobotics/inspiration_ftc#5]
@kolinbilly What are the individual tasks for completing this?

- [ ] insert photos
- [ ] noahtang17@gmail.com please provide input why we took this screenshot with coach Mike
- [ ] kolinszeto@gmail.com need parameter screenshot to shwo the growth of the team in CAD capabilities for drivetrian 
- [ ] kolinszeto@gmail.com need calcualtions for speed calculations, comaprring the linakge speed verse the spools attached ontot he servos
- [ ] kolinszeto@gmail.com need to insert sensor holder images for documentation
- [ ] kolinszeto@gmail.com need pictures for the sensor holders
- [ ] rainashapur@gmail.com please place your lessons learned in attempting to reassemble the auto arm
- [ ] shreyasvrangan@gmail.com please provide a description and lessons learned for cutting the ocrner off auto arm plate to allow for interface witht eh phone holder
- [ ] kolinszeto@gmail.com need to add in renders for final robto here

**Comment by colin-szeto** [comment]
- [ ] Colin update the screenshots to lessons learned

- [ ] make a CAD to on real robot page

- [ ] one pagers for description of robots
